version: '3'
services:
    php-fpm:
        image: php
        container_name: php-fpm
        networks:
          - web
        ports:
          - "9000:9000"
        volumes:
          - /etc/$YOUR_DOMAIN_NAME$/www:/usr/share/nginx/html
          - /etc/$YOUR_DOMAIN_NAME$/forum:/usr/share/nginx/html/forum
        stdin_open: true
        tty: true
    php-nginx:
        image: nginx
        container_name: php-nginx
        networks:
          - web
        ports:
          - "443:443"
          - "80:80"
        volumes:
          - /etc/$YOUR_DOMAIN_NAME$/www:/usr/share/nginx/html
          - /etc/$YOUR_DOMAIN_NAME$/forum:/usr/share/nginx/html/forum
          - /etc/$YOUR_DOMAIN_NAME$/nginx.conf:/etc/nginx/nginx.conf
          - /etc/$YOUR_DOMAIN_NAME$/cert:/etc/nginx/cert
        depends_on:
          - php-fpm
    DB:
        image: mysql
        container_name: DB
        networks:
          - web
        ports:
          - "3306:3306"
        environment:
            MYSQL_ROOT_PASSWORD: $YOUR_PASSWORD$
        volumes:
          - /etc/$YOUR_DOMAIN_NAME$/DB:/var/lib/mysql
        depends_on:
          - php-fpm
networks:
    web:
